site_name: Assimilator - the best Python patterns
site_description: Assimilator Python framework, Domain-Driven Design, DDD, high performance, easy to learn, fast to code
theme:
  name: material
  logo: images/logo.png
  favicon: images/icon.png
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
nav:
  - Introduction: index.md
  - ✨New in 1.2.0✨: new_changes.md
  - Concepts: concepts.md
  - Basic tutorials:
    - Important things: tutorial/important.md
    - Database tutorial: tutorial/database.md
    - Advanced database tutorial: tutorial/advanced_database.md
    - Architecture tutorial: tutorial/architecture_tutorial.md
    # - Events tutorial: tutorial/events.md
  - SQLAlchemy:
    - Database: alchemy/database.md
    # - Events: alchemy/events.md
  - Internal:
    - Database: internal/database.md
    # - Events: internal/events.md
  # - Kafka:
    # - Events: kafka/events.md
  - Redis:
    - Database: redis/database.md
    # - Events: redis/events.md
  - MongoDB:
    - Database: mongo/database.md
  - Services Tutorial: services.md
  - Unidentified Patterns: unidentified_patterns.md
  - Video Tutorials: video_tutorials.md

repo_url: https://github.com/knucklesuganda/py_assimilator
repo_name: knucklesuganda/py_assimilator
site_author: Andrey Ivanov | Python
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  analytics:
    provider: google
    property: G-7PEMV9YSS5

